### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by borisdiakur** [danielstern/ngAudio#50]
Steps to reproduce:
1. Open the bin: http://jsbin.com/wuhita/2/edit?html,js,console,output
2. Click on the big "click me" and see the error pop up in the browser console.

Expected behaviour: Sound plays, no error messages.
Current behaviour: Sound plays, got error message.

Here is the bin exported to Gist (just in case...): https://gist.github.com/borisdiakur/d351a01726a17a9ce741

**Comment by saiichihashimoto** [comment]
I can report the same thing. When ngAudio.load in the link property of the directive, I won't get the error, regardless of when/where it plays. If I load it within a $scope.$watch(...), it displays the same error.

**Comment by danielstern** [comment]
The simplest solution seems to be just to defend the offending (and much maligned) lines of code, but they were put in for mobile support, so we don't want to break iPad and Android support.

Anyone want to take a crack at this one?

**Comment by borisdiakur** [comment]
To me the simplest solution seems to be this:

    window.addEventListener("click",function twiddle(){
        if (audio) {
            audio.play();
            audio.pause();
        }
        window.removeEventListener("click",twiddle);
    });

Though I do not see the whole picture.

**Comment by danielstern** [comment]
The best is to implement the fix in a branch, then test that branch on several devices including a desktop, an android and an iPhone running IOS7 and IOS8 if possible.

**Comment by fnagel** [comment]
I've run into this problem as well. Funny thing is: I use ngAudio from my controller (fired by a animation callback). Here is what my controller looks like:

````
angular.module( 'app' )
	.controller( 'ctrl', function( $scope, ngAudio ) {
		var sound = ngAudio.load( '../app/sounds/my-sound.mp3');

		$scope.myCallback = function() {
			sound.play();
		};
	} );

````

When the controller is called first time everything works just fine. Second time I got the above mentioned error. Any suggestions?

**Comment by danielstern** [comment]
@fnagel The official recommendation would be to leave everything as it is if this is not breaking your app, as this is an artifact of supporting mobile devices and changing the inner-workings of the directive could reduce (or... improve?) mobile support.
If you do make any changes to the directive, be certain to check for regression on mobile.

**Comment by ArTiSTiX** [comment]
The issue may be caused by the load function which is deferred, but not the eventListener.

For a reason I can't explain, my first call to load is not buggy. But when i try to load the file again (I don't know if it's buggy when loading a new one), the audio variable is not initialized yet, causing a console log.

In my opinion, @borisdiakur's solution may not be the best, since this function is not supposed to be bypassed for iOS. I think you should try to move the eventListener binding inside the load promise callback, since the audio must be loaded/initialized before being played.

**Comment by PavelKonon** [comment]
I think a solution from @borisdiakur is most easiest way to fight an issue. We need something to not receive errors in console when using this lib.

**Comment by danielstern** [comment]
This is resolved in 1.4.2 

https://github.com/danielstern/ngAudio/issues/43

**Comment by PavelKonon** [comment]
Still reproduces in Chrome -- http://jsfiddle.net/pavelk/mLrsLt4b/ -- see console output.

**Comment by danielstern** [comment]
Hey @PavelKonon 

As referenced, you need to disable unlock if you don't want that error.

http://jsfiddle.net/0ue6rceo/

**Comment by pharingee** [comment]
Hey @danielstern

Disabling unlock causes playback issues on mobile. Isn't there a way to solve the issue such that  playback on mobile browsers isn't affected?

**Comment by danielstern** [comment]
No way that I know of. Anyone have any ideas?

**Comment by lvovgeka** [comment]
Hi, can stick this crutch up there. http://joxi.ru/zANjeKaU7EGeA9
