### ISSUE TITLE
Error "Uncaught TypeError: Cannot read property 'play' of undefined"

### ISSUE THREAD

**Issue by tobilg** [danielstern/ngAudio#85]
When using the `ngAudio.play()` method with a remote resource, I receive the above error on my console (version is 1.7.0 on the latest Chrome).

It fails at `audio.play();`, what leads me to the assumption that `audio` has not yet been initialized upon calling.

```
if (ngAudioGlobals.unlock) {

            window.addEventListener("click",function twiddle(){
                audio.play();
                audio.pause();
                window.removeEventListener("click",twiddle);
            });

        }
}
```

Furthermore, I think I'm unable to set `ngAudio.unlock = false` as outlined at http://danielstern.github.io/ngAudio/#/docs

**Comment by lbyers** [comment]
Hard to reliably reproduce (it is a race condition) but I have noted this behavior as well. I submitted a PR which moves that call into the closure that assigns the audio property.

**Comment by tsareg** [comment]
+1

**Comment by danielstern** [comment]
Fixed in PR

**Comment by danielcrisp** [comment]
Is the fixed version available through bower? I don't see it

**Comment by danielstern** [comment]
Fix should be somewhere here: 

https://github.com/danielstern/ngAudio/pulls?q=is%3Apr+is%3Aclosed

If not, please take a look and see if you can implement a fix / update the necessary bower versioning to make the fix available.

**Comment by danielcrisp** [comment]
I think you just need to push a new version / tag

I still see the old code here for v1.7.0

https://github.com/danielstern/ngAudio/blob/1.7.0/app/angular.audio.js#L145-L153

**Comment by danielstern** [comment]
Hey @danielcrisp,

I added you as a collaborator, so please feel free to push the new tag.

Cheers,
DS

**Comment by danielcrisp** [comment]
Thanks, done
